### ISSUE TITLE
Hashtables 1.2.2.0 should be marked as depending on base >= 4.7

### ISSUE THREAD

**Issue by fizbin** [gregorycollins/hashtables#42]
The dependencies on hashtables-1.2.2.0 as listed on hackage are incorrect. It is listed as requiring `base (==4.*)` but should list the dependencies as `base (>= 4.7.0.0 && < 5)`

The code will not compile on ghc 7.6.3:

```
Downloading hashtables-1.2.2.0...
Configuring hashtables-1.2.2.0...
Building hashtables-1.2.2.0...
Preprocessing library hashtables-1.2.2.0...
[ 1 of 12] Compiling Data.HashTable.Internal.UnsafeTricks ( src/Data/HashTable/Internal/UnsafeTricks.hs, dist/build/Data/HashTable/Internal/UnsafeTricks.o )
[ 2 of 12] Compiling Data.HashTable.Internal.IntArray ( src/Data/HashTable/Internal/IntArray.hs, dist/build/Data/HashTable/Internal/IntArray.o )

src/Data/HashTable/Internal/IntArray.hs:74:19:
    Not in scope: `finiteBitSize'
Failed to install hashtables-1.2.2.0
```

**Comment by peti** [comment]
I've run into the same issue while trying to compile `jhc`, which depends on this package. A proper version constraint on `base` would be very much appreciated so that `cabal-install` has a chance to pick up an older version for the build plan.

**Comment by fizbin** [comment]
Though in light of issue #41, maybe it should be listed as requiring base version >= 4.8
